import { prisma } from '@/lib/db';
import { startOfTodayZA } from '@/lib/format';

/**
 * Read helpers for the public site. Presentation components never touch
 * Prisma directly — they receive plain data from these functions.
 *
 * During `next build` an unreachable database yields empty content (the page
 * is then regenerated by ISR); at runtime errors propagate so Next keeps
 * serving the last good page instead of caching an empty one.
 */
export async function safeQuery<T>(fn: () => Promise<T>, fallback: T): Promise<T> {
  try {
    return await fn();
  } catch (error) {
    if (process.env.NEXT_PHASE === 'phase-production-build') {
      console.warn('[public-data] query failed during build, using fallback');
      return fallback;
    }
    throw error;
  }
}

export const getUpcomingEvents = (take = 20) =>
  safeQuery(
    () =>
      prisma.event.findMany({
        where: {
          eventDate: { gte: startOfTodayZA() },
          status: 'SCHEDULED',
          displayOnWebsite: true,
        },
        include: { ministry: { select: { name: true, slug: true } } },
        orderBy: [{ eventDate: 'asc' }],
        take,
      }),
    [],
  );

export const getWebsiteMinistries = (take?: number) =>
  safeQuery(
    () =>
      prisma.ministry.findMany({
        where: { isActive: true, displayOnWebsite: true },
        orderBy: { sortOrder: 'asc' },
        take,
      }),
    [],
  );

/** Featured sermon first (same ordering as /api/sermons), then newest. */
export const getRecentSermons = (take = 4) =>
  safeQuery(
    () =>
      prisma.sermon.findMany({
        orderBy: [{ isFeatured: 'desc' }, { sermonDate: 'desc' }],
        take,
      }),
    [],
  );
